NODE_ENV: development
PORT: 7500

IPV4VW: http://10.2.0.184
IPV6VW: http://[2001:6a8:1d80:2021:230:48ff:fe78:f542]

IPV4LOCAL: http://192.168.0.142
IPV6LOCAL: http://[2a02:1811:c411:c100:f878:554d:5db9:204b]

STAGINGVW: false
USEIPV6: false
